# Welcome to Jekyll!

# Site settings
title       : "Adi Linden"
description : "Reflections of a Wandering Mind"
url         : http://adis.ca
baseurl     : ""  # without trailing slash

comments: true
disqus_shortname      : "adilinden"
google_verify         : "RBz5-YgaAL6kroz0uHk40Uboacv9vE9hZC77dXqmy0I"

# Author settings
author:
  name      : Adi Linden
  bio       : "Networking, VMware, Unix professional; Electronics, amateur radio, programming geek; Photography enthusiast; Hobby cook and baker."
  thumb     : /resources/images/me_charcoal-120.jpeg
  email     : mailto:adi57@adis.ca
  github    : http://github.com/adilinden
  twitter   : http://twitter.com/adilinden
  facebook  : http://facebook.com/adilinden
  linkedin  : http://ca.linkedin.com/in/adilinden

# Build settings
permalink: /entry/:year/:title/
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: false
    line_numbers: false

gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

paginate: 6
paginate_path: /journal/:num/

destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CHANGES.md
  - run.sh
  - _config.yml
  - _config_dev.yml

